version: "3.1"

services:
  dna-middleware:
    image: "kwlee0220/dna-middleware:0.0.0"
    container_name: dna-middleware
    ports:
      - "3000:3000"
    environment:
      DNA_MW_JDBC_CONNECT: 192.168.35.101:5432
      DNA_MW_JDBC_DB: basic
      DNA_MW_JDBC_USER: postgres
      DNA_MW_JDBC_PASSWD: ictway001

      DNA_MW_RABBITMQ_CONNECT: 192.168.35.193:5672
      # DNA_MW_RABBITMQ_ID: dna
      # DNA_MW_RABBITMQ_PASSWD: urc2004

      DNA_MW_KAFKA_SERVERS: "192.168.35.193:9091,192.168.35.193:9092,192.168.35.193:9093"

      DNA_MW_WEBSOCK_HOST: 192.168.35.193
      DNA_MW_WEBSOCK_PREVIEW_PORT: 8870
      DNA_MW_WEBSOCK_REPLAY_PORT: 8880
      DNA_MW_WEBSOCK_STREAM_PORTS: 8881,8882,8883,8884
