version: "3.1"

services:
  dna-middleware:
    image: "kwlee0220/dna-middleware:0.0.0"
    container_name: dna-middleware
    environment:
      DNA_MW_JDBC_CONNECT: 192.168.0.12:5432
      # DNA_MW_JDBC_DB: dna
      # DNA_MW_JDBC_USER: dna
      # DNA_MW_JDBC_PASSWD: urc2004

      DNA_MW_RABBITMQ_CONNECT: 192.168.0.12:5672
      # DNA_MW_RABBITMQ_ID: dna
      # DNA_MW_RABBITMQ_PASSWD: urc2004

      DNA_MW_KAFKA_SERVERS: "192.168.0.12:9091,192.168.0.12:9092,192.168.0.12:9093"

      DNA_MW_WEBSOCK_HOST: 129.254.82.26
      DNA_MW_WEBSOCK_PREVIEW_PORT: 8870
      DNA_MW_WEBSOCK_REPLAY_PORT: 8880
      DNA_MW_WEBSOCK_STREAM_PORTS: 8881,8882,8883,8884
